### ISSUE TITLE
New items arent diplayed in the toolbar

### ISSUE THREAD

**Issue by afaure42** [FishFoxFederation/ft_vox#111]
I added a wood block in the Block.cpp file as well as the Item.cpp file
I added the texture in the assets folder and the path to the texture
I added the item id to the toolbar of the player

I can place wooden blocks with no problems but the item isnt displayed in the toolbar

Is there another step that i missed or is this a bug ?

**Comment by SaumonDesMers** [comment]
There was a local variable toolbar_items that overwritten the toolbar_item passed through the world scene. That's why the new items didn't show up.
This issue is already solved in another branch so I'm going to close it.
